places = ['japan', 'usa', 'england', 'dubai', 'germany']

print(f"{places}\n")
print(f"{sorted(places)}\n")
print(f"{places}\n")
print(f"{sorted(places, reverse=True)}\n")
print(f"{places}\n")
places.reverse()
print(f"{places}\n")
places.reverse()
print(f"{places}\n")
places.sort()
print(f"{places}\n")
places.sort(reverse=True)
print(f"{places}")